Sync from JHUGenMELA
usarica/HiggsAnalysis-ZZMatrixElement pull request #56
Opened 2018-12-27 14:31 UTC by hroskes

2019-01-07 13:29 UTC, usarica requested changes
There does not seem to be any need to move EvalAlphaS function. I also do not see this need in the original generator. What was the reason to move?

2019-01-07 13:47 UTC, hroskes commented
I think you already know the answer: I moved it here because Yaofu moved in JHUGen.  For the reason for that, you'll have to ask him.  Does it really matter where it is?

2019-01-07 13:49 UTC, usarica commented
We should avoid making unnecessary changes, and also collect functions where they belong. Otherwise we are going to bloat mod_Parameters in the future to an incomprehensible module. Under this consideration of the future, yes, it does matter a bit.

2019-01-24 15:55 UTC, usarica approved these changes

2019-01-24 15:55 UTC, merged